// crypto.js
//
// Shared cryptographic helpers used by BOTH the service worker (background.js)
// and the popup (popup.js). This module is intentionally dependency-free and
// uses only the WebCrypto API (crypto.subtle + crypto.getRandomValues), which
// is available in MV3 service workers and extension pages alike.
//
// SECURITY DESIGN NOTES
// ---------------------
// * We NEVER store the password in plaintext. We store only a PBKDF2-SHA256
//   derivation: {salt, iterations, hashB64}. This is the same shape used by
//   background.js when persisting to chrome.storage.local.
// * PBKDF2 with >= 210,000 iterations of SHA-256 follows OWASP's 2023 guidance
//   for PBKDF2-HMAC-SHA256. The iteration count is stored alongside the hash so
//   it can be raised in the future without breaking existing installs.
// * Verification uses a constant-time comparison of the derived bits to avoid
//   leaking information through timing side channels.
// * The autogenerated default password draws 24 characters from a 90-character
//   charset using crypto.getRandomValues with rejection sampling (no modulo
//   bias), giving ~155 bits of entropy (24 * log2(90) ≈ 155.8).
//
// This file is loaded as an ES module (import ... from './crypto.js').

import { COMMON_PASSWORDS } from './common-passwords.js';

// PBKDF2 parameters. 210k iterations >= the 210,000 minimum requested and is a
// reasonable balance of security vs. unlock latency in a service worker.
export const PBKDF2_ITERATIONS = 210000;
const PBKDF2_HASH = 'SHA-256';
const DERIVED_BITS = 256; // 32 bytes of derived key material
const SALT_BYTES = 16; // 128-bit random salt

// Charset for autogenerated access codes: an unambiguous, paste-safe alphabet
// (Base58 — letters + digits, minus the look-alikes 0/O, 1/I/l). Deliberately
// NO symbols: the code is copied from the popup and pasted/sent as a bearer
// credential, so we optimize for "select-all, paste, done" — no leading/trailing
// punctuation to lose, no shell-quoting or JSON-escaping hazards. 58 chars gives
// log2(58) ≈ 5.86 bits each; at length 24 that's ~140.6 bits, far above the
// 60-bit policy floor. Users who WANT symbols can still set a custom passphrase.
const GEN_CHARSET =
  'ABCDEFGHJKLMNPQRSTUVWXYZ' +
  'abcdefghijkmnopqrstuvwxyz' +
  '23456789';

const GEN_DEFAULT_LENGTH = 24;

// ---------------------------------------------------------------------------
// Base64 helpers (work on ArrayBuffer / Uint8Array).
// ---------------------------------------------------------------------------

function bytesToBase64(bytes) {
  const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let binary = '';
  for (let i = 0; i < arr.length; i++) {
    binary += String.fromCharCode(arr[i]);
  }
  return btoa(binary);
}

function base64ToBytes(b64) {
  const binary = atob(b64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    out[i] = binary.charCodeAt(i);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Random password generation
// ---------------------------------------------------------------------------

/**
 * Generate a cryptographically strong random password.
 *
 * Uses rejection sampling over crypto.getRandomValues to avoid modulo bias:
 * we only accept random bytes below the largest multiple of the charset size
 * that fits in a byte. With the 58-char paste-safe charset and length 24,
 * entropy is ~24 * log2(58) ≈ 140.6 bits (far above the 60-bit policy floor).
 *
 * @param {number} [length=24]
 * @returns {string}
 */
export function generatePassword(length = GEN_DEFAULT_LENGTH) {
  const charsetLen = GEN_CHARSET.length;
  // Largest multiple of charsetLen that fits in [0, 256) — bytes >= this are
  // rejected so every accepted byte maps uniformly onto the charset.
  const limit = Math.floor(256 / charsetLen) * charsetLen;
  const out = [];
  const buf = new Uint8Array(1);
  while (out.length < length) {
    crypto.getRandomValues(buf);
    const b = buf[0];
    if (b < limit) {
      out.push(GEN_CHARSET[b % charsetLen]);
    }
  }
  return out.join('');
}

// ---------------------------------------------------------------------------
// PBKDF2 hashing + verification
// ---------------------------------------------------------------------------

async function deriveBits(password, saltBytes, iterations) {
  const enc = new TextEncoder();
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    enc.encode(password),
    { name: 'PBKDF2' },
    false,
    ['deriveBits']
  );
  const bits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: saltBytes,
      iterations,
      hash: PBKDF2_HASH,
    },
    keyMaterial,
    DERIVED_BITS
  );
  return new Uint8Array(bits);
}

/**
 * Hash a password for storage.
 * @param {string} password
 * @param {number} [iterations=PBKDF2_ITERATIONS]
 * @returns {Promise<{salt:string, iterations:number, hashB64:string}>}
 *   salt is base64-encoded; store this object verbatim in chrome.storage.local.
 */
export async function hashPassword(password, iterations = PBKDF2_ITERATIONS) {
  const salt = new Uint8Array(SALT_BYTES);
  crypto.getRandomValues(salt);
  const derived = await deriveBits(password, salt, iterations);
  return {
    salt: bytesToBase64(salt),
    iterations,
    hashB64: bytesToBase64(derived),
  };
}

/**
 * Verify a password against a stored record produced by hashPassword().
 * Uses a constant-time comparison to avoid timing side channels.
 * @param {string} password
 * @param {{salt:string, iterations:number, hashB64:string}} record
 * @returns {Promise<boolean>}
 */
export async function verifyPassword(password, record) {
  if (!record || !record.salt || !record.hashB64 || !record.iterations) {
    return false;
  }
  const salt = base64ToBytes(record.salt);
  const expected = base64ToBytes(record.hashB64);
  const derived = await deriveBits(password, salt, record.iterations);
  return constantTimeEqual(derived, expected);
}

/**
 * Constant-time comparison of two byte arrays. Returns false immediately on a
 * length mismatch (length is not itself secret here), otherwise ORs together
 * the XOR of every byte pair so the running time does not depend on WHERE the
 * first difference occurs.
 * @param {Uint8Array} a
 * @param {Uint8Array} b
 * @returns {boolean}
 */
export function constantTimeEqual(a, b) {
  if (!(a instanceof Uint8Array)) a = new Uint8Array(a);
  if (!(b instanceof Uint8Array)) b = new Uint8Array(b);
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a[i] ^ b[i];
  }
  return diff === 0;
}

// ---------------------------------------------------------------------------
// Entropy estimation + password policy
// ---------------------------------------------------------------------------

/**
 * Estimate the entropy (in bits) of a password.
 *
 * Model: entropy of a source that draws each character uniformly from a pool
 * whose size is inferred from the character CLASSES present (Shannon entropy of
 * a uniform-over-pool source is log2(pool) bits per character). We then apply a
 * repetition penalty so degenerate strings like "aaaaaaaaaaaa" — which have a
 * large nominal pool but almost no real variety — are scored low:
 *
 *   effectiveLength = uniqueChars + 0.5 * (length - uniqueChars)
 *   entropy         = effectiveLength * log2(poolSize)
 *
 * This keeps the estimate consistent with the 12-char minimum (a strong,
 * mixed-class 12+ char password clears 60 bits) while still rejecting long but
 * repetitive strings. It is a heuristic, NOT a substitute for zxcvbn, and is
 * intentionally dependency-free.
 *
 * @param {string} str
 * @returns {number} estimated entropy in bits
 */
export function estimateEntropy(str) {
  if (!str || str.length === 0) return 0;
  const chars = Array.from(str); // handle surrogate pairs / unicode correctly

  // Infer the character pool from the classes that actually appear.
  let pool = 0;
  let hasLower = false, hasUpper = false, hasDigit = false, hasSymbol = false, hasUnicode = false;
  for (const ch of chars) {
    const code = ch.codePointAt(0);
    if (code > 127) hasUnicode = true;
    else if (ch >= 'a' && ch <= 'z') hasLower = true;
    else if (ch >= 'A' && ch <= 'Z') hasUpper = true;
    else if (ch >= '0' && ch <= '9') hasDigit = true;
    else hasSymbol = true; // printable ASCII punctuation/space
  }
  if (hasLower) pool += 26;
  if (hasUpper) pool += 26;
  if (hasDigit) pool += 10;
  if (hasSymbol) pool += 33; // ASCII symbols + space
  if (hasUnicode) pool += 100; // conservative allowance for the unicode range
  if (pool === 0) pool = 1;

  // Repetition penalty via an "effective length".
  const uniqueChars = new Set(chars).size;
  const length = chars.length;
  const effectiveLength = uniqueChars + 0.5 * (length - uniqueChars);

  return effectiveLength * Math.log2(pool);
}

/**
 * Enforce a NIST SP 800-63B-aligned password policy.
 *
 * Rules:
 *  - Minimum length 12 (NIST recommends >= 8; we require 12).
 *  - Allow ALL printable characters including spaces and unicode (no composition
 *    rules, per NIST guidance against arbitrary complexity requirements).
 *  - Reject passwords appearing in the bundled common-password blocklist
 *    (NIST: screen against known-compromised/common values). Case-insensitive.
 *  - Require estimated Shannon entropy >= 60 bits (a local heuristic on top of
 *    the NIST baseline to reject low-quality-but-long strings like "aaaa...").
 *
 * @param {string} pw
 * @returns {{ok: boolean, reasons: string[]}}
 */
export function validatePasswordPolicy(pw) {
  const reasons = [];
  if (typeof pw !== 'string' || pw.length === 0) {
    return { ok: false, reasons: ['Password must not be empty.'] };
  }
  // NIST allows very long passphrases; a sane upper bound avoids DoS on PBKDF2.
  if (pw.length > 256) {
    reasons.push('Password must be at most 256 characters.');
  }
  if (pw.length < 12) {
    reasons.push('Password must be at least 12 characters.');
  }
  // Common-password blocklist (case-insensitive, trimmed).
  const normalized = pw.trim().toLowerCase();
  if (COMMON_PASSWORDS.has(normalized)) {
    reasons.push('Password is too common; choose something less predictable.');
  }
  const entropy = estimateEntropy(pw);
  if (entropy < 60) {
    reasons.push(
      `Password is too predictable (estimated ${entropy.toFixed(1)} bits; need >= 60).`
    );
  }
  return { ok: reasons.length === 0, reasons };
}

/**
 * Generate a random session token: 32 random bytes rendered as 64 hex chars.
 * @returns {string}
 */
export function generateToken() {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  let hex = '';
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i].toString(16).padStart(2, '0');
  }
  return hex;
}
